apiVersion: v1
kind: Pod1
metadata:
  name: pod-2
  labels:
    type: web
    lo: dev
spec:
  containers:
  - name: container
    image: kubetm/init
---
apiVersion: v1
kind: Pod2
metadata:
  name: pod-2
  labels:
    type: db
    lo: dev
spec:
  containers:
  - name: container
    image: kubetm/init
---
apiVersion: v1
kind: Pod3
metadata:
  name: pod-2
  labels:
    type: server
    lo: dev
spec:
  containers:
  - name: container
    image: kubetm/init
---
apiVersion: v1
kind: Pod4
metadata:
  name: pod-2
  labels:
    type: web
    lo: production
spec:
  containers:
  - name: container
    image: kubetm/init
---
apiVersion: v1
kind: Pod5
metadata:
  name: pod-2
  labels:
    type: db
    lo: production
spec:
  containers:
  - name: container
    image: kubetm/init
---
apiVersion: v1
kind: Pod6
metadata:
  name: pod-2
  labels:
    type: server
    lo: production
spec:
  containers:
  - name: container
    image: kubetm/init
---
